// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbulnaibcqdsjjpgvcgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidWxuYWliY3Fkc2pqcGd2Y2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODQ5NzMsImV4cCI6MjA4Nzg2MDk3M30.x95Py1l5zoaXDoXEez7K8VsLfZK_IfEwzG5iQRDXplg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});